import React, { useState, useEffect } from 'react';
import type { NextPage, GetStaticProps, GetServerSideProps } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import prisma from '../lib/prisma';
import mainStyles from '../styles/Home.module.scss';
import buttonStyles from '../styles/Button.module.scss';
import Header from '../components/Header';
import DialogContainer from '../components/Dialog';

enum Role {
  ADMIN = 'ADMIN',
  USER = 'USER',
  DEVELOPER = 'DEVELOPER',
  DESIGNER = 'DESIGNER',
  PROJECT_MANAGER = 'PROJECT_MANAGER'
}

export type ProfileProps = {
  id: string;
  image: string;
  bio: string;
  role: Role;
  userId: string;
};

export type UserProps = {
  id: string;
  email: string;
  name: string;
  profile: ProfileProps | null;
};

export type SubtaskProps = {
  id: string;
  title: string;
  isCompleted: boolean;
  taskId: string;
};

export type TaskProps = {
  id: string;
  title: string;
  description: string;
  status: string;
  columnId: string;
  subTasks: SubtaskProps[];
};

export type ColumnProps = {
  id: string;
  name: string;
  tasks: TaskProps[];
  boardId: string;
};

export type BoardProps = {
  id: string;
  name: string;
  columns: ColumnProps[];
};

const Home = (users: UserProps[], boards: BoardProps[]) => {
  const [loading, setLoading] = useState(false);
  const [showDialog, setShowDialog] = useState(false);

  const open = () => {
    setShowDialog(true);
  };

  const close = () => {
    setShowDialog(false);
  };

  useEffect(() => {
    if (!loading) {
      console.log(users);
      console.log(boards);
    }

    setLoading(true);
  }, []);

  return (
    <div className="wrapper">
      <Header />
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={mainStyles.main}>
        <h1 className={mainStyles.emptyBoardTitle} style={{ marginBottom: '24px' }}>
          This board is empty. Create a new column to get started.
        </h1>
        <button
          role="button"
          type="button"
          aria-label="Add New Task"
          className={mainStyles.emptyBoardButton}
        >
          <Image src="/icon-add-task-mobile.svg" width={12} height={12} />
          <span style={{ marginLeft: '4px' }}>Add New Column</span>
        </button>
      </main>

      <div id="dialog-root"></div>
    </div>
  );
};

export const getServerSideProps: GetServerSideProps = async () => {
  try {
    const users = await prisma.user.findMany({
      include: { profile: true }
    });

    const boards = await prisma.board.findMany({
      include: { columns: true }
    });

    return {
      props: { users, boards }
    };
  } catch (error) {
    console.error(error);
    throw error;
  }
};

export default Home;
